### ISSUE TITLE
Clean lesson

### ISSUE THREAD

**Issue by Ylja** [data-lessons/library-python-intro#1]
- [ ] Remove Pandas lesson
- [ ] Remove old introduction
- [ ] Changes authors,
- [ ] Change maintainers

**Comment by drjwbaker** [comment]
Hey @Ylja. Are you able to add a 'mozsprint' label to this issue? I can't for some reason..

**Comment by mkuzak** [comment]
@drjwbaker, unfortunately, you need privileges to add labels, so that needs to be maintainers task

**Comment by cmacdonell** [comment]
The PR is still pending for this, did you mean to close it @mkuzak?
