### ISSUE TITLE
Change references to Jupyter notebooks

### ISSUE THREAD

**Issue by richyvk** [data-lessons/library-python-intro#11]
The decision was made some time ago (ask Belinda for details) that the Spyder IDE was going to be used for teaching Python instead of Jupyter notebooks, which had previously been used and still are in at least some Software Carpentry lessons including the gapminder lesson this lesson is based on.

I've edited the setup file to reflect this, but we will need to go through each of the episodes and replace Jupyter notebook references and examples to use Spyder instead.

e.g. Episode 1: Running and Quitting has a lot of stuff in it about running a notebook. I think we need to replace this with a quick intro to using Spyder.

**Comment by Ylja** [comment]
I will pick this up, we were not to happy with the first episode as it is atm anyway. The librarian here found himself skipping over half the text.
