### ISSUE TITLE
Sprint day two - Brisbane - report

### ISSUE THREAD

**Issue by richyvk** [data-lessons/library-python-intro#15]
Hi all

Petrina Collingwood (@prcollingwood) and I both worked on the lesson today. I cleaned up some of the config and index and started on an introduction - I'm going to carry on with that this evening.

Petrina started working through each episode changing things to be less gapminder/software carpentry, and more library carpentry - focusing on changing code examples. She looked at episdoes 2 & 3.

Then @laufers @elainewong and @weaverbel did some stuff.

There's a few outstanding issues if anyone wants to tackle them. I'm on zoom for a bit tongith so let me know if you want to chat.

**Comment by prcollingwood** [comment]
@richyvk Just so you know, I looked at all the episodes up to lunch, but only no.s 2 and 3 needed changes.

**Comment by richyvk** [comment]
Closing this - no longer needed
