### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by Ylja** [data-lessons/library-python-intro#2]

**Comment by richyvk** [comment]
Added myself. I'm happy to do it if no-one objects. Would be great to have someone else too though :)

**Comment by elainewong** [comment]
@richyvk I'll help you out!

**Comment by weaverbel** [comment]
Awesome ! Adding the pycar lesson as an issue. https://github.com/ireapps/pycar

**Comment by c-martinez** [comment]
@elainewong -- making you maintainer, invitation sent.
