### ISSUE TITLE
move, reduce, or extract out the markdown instructions

### ISSUE THREAD

**Issue by elliewix** [data-lessons/library-python-intro#34]
I worry that focusing on markdown syntax so early might distract learners and take away valuable time. it's also a pretty huge amount of text on the screen. Perhaps simplify it to state that you can markup the text with markdown, and then have a side lesson on markdown in jupyter that can be referenced later.  I'm a little torn about this, thus the issue.  

The included commands are all good formatting things to do, but it might inspire a lengthy tangental lecture and demo.  So maybe focus on two essentials:  making H1 headers and single-level lists.  Then linking out to a side/sub lesson for students to explore during the challenge portion, and have them expand on those tasks as part of the challenge.

Example:  "Use the information from the markdown lesson to add a lower level header to your cell..."

**Comment by c-martinez** [comment]
We might have gotten rid of all the Markdown stuff because of not using Jupyter.

I'll close this issue for now, but please re-open it if there is still some markdown content which I have missed.
