### ISSUE TITLE
Updating language and examples to be more library relevant 

### ISSUE THREAD

**Issue by sclayton29** [data-lessons/library-python-intro#4]
Making an issue to go along with @richyvk day one report (https://github.com/data-lessons/library-python-intro-superseded/issues/2).  

I'm going to get started on this, but anyone else can jump in if they want!

**Comment by prcollingwood** [comment]
I checked the episodes up to lunch. Some of them didn't need changing. Belinda merged the ones I updated.

**Comment by c-martinez** [comment]
@sclayton29, do you think this is still the case? could we perhaps have a list of which episodes need to be updated / have been updated?

**Comment by richyvk** [comment]
I'm closing this issue, because I think we've gone past this stage. Updating the language and examples generally is ongoing.
